apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment
  labels:
    app: appdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdeployment
  template:
    metadata:
      labels:
        app: appdeployment
    spec:
      containers:
      - name: appdeployment
        image: gcr.io/emerald-water-235319/hello-devops-image:current
        env:
        - name: MONGO_HOST
          value: mongodb
        ports:
        - containerPort: 8080
