substitutions:
    _CLOUDSDK_COMPUTE_ZONE: us-east1-b # default value
    _CLOUDSDK_CONTAINER_CLUSTER: hellodevops-automated-cluster     # default value
steps:
- id: clone-repo
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/giriarte/devopspoc.git']
- id: create-cluster
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'container',
      'clusters', 'create', 'hellodevops-automated-cluster',
      '--zone', '${_CLOUDSDK_COMPUTE_ZONE}',
      '--num-nodes', '1'
    ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
- id: kubectl-apply
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'hellodevops/docker/k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
images: ['eu.gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:php-$SHORT_SHA']
AKIAXDUJO2VTGG3ZA372
qC0Q4++jtXXHjykE1YUoBXoGKyaIR+0cxy5uxQ/1
