substitutions:
    _CLOUDSDK_COMPUTE_ZONE: us-central1-a # default value
    _CLOUDSDK_CONTAINER_CLUSTER: ci-cluster     # default value
steps:
- id: kubectl-apply
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'hellodevops/docker/k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
