substitutions:
    _CLOUDSDK_COMPUTE_ZONE: us-central1-a # default value
    _CLOUDSDK_CONTAINER_CLUSTER: ci-cluster     # default value
steps:
- id: clone-repo
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/giriarte/devopspoc.git']
- id: clean-install
  name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install', '-DskipTests']
  dir: hellodevops
- id: unit-tests
  name: 'gcr.io/cloud-builders/mvn'
  args: ['test']
  dir: hellodevops
- id: create-docker-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-devops-image:current', '-f', 'hellodevops/docker/app_Dockerfile', '.']
- id: push-docker-image
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello-devops-image:current']
- id: kubectl-apply
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['replace', '--force', '-f', 'hellodevops/docker/k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
